### ISSUE TITLE
Better serach

### ISSUE THREAD

**Issue by majkinetor** [antonmedv/walk#55]
1. Search input is temporary and you can't select next match with some hotkey
    2. you can't refine search because it dissapears
1. It would be great to add option to filter out the fuzzy search results as one types.

**Comment by antonmedv** [comment]
I guess this is filtering. We can think on adding a separate key for filtering.

Think of `/` as a fuzzy jump.

**Comment by TheReptar** [comment]
Looking at the key bindings in [~/main.go](https://github.com/antonmedv/llama/blob/master/main.go#L33) I think `shift+/` would be an ideal key combo for filtering.

It's consistent with other binding schemes, lets the user track similar functionality (fuzzy jump & filter) to the same key `/`, and the character generally produced by the `shift+/` combo (`?`) is well-associated with the act of querying/filtering.

**Comment by santhoshr** [comment]
I have some some changes done quickly for filtering, mostly hack on this code (btw I don't know Go, found it very simple and pleasant ! from Java developer) and thanks for sharing this code @antonmedv more than full fledged file manager this is nice for quick navigation and finding stuff, made some changes on variable names to implement filter, search, parent navigation, so instead of pull request I'm mentioning it here so you guys can take a look, like 'tab' key to flip search or filter or double tab to switch on or off, I also have space bar for toggling between search / filter and navigating with vim keys. You can repeatedly filter and reload list (R) to restart filtering

https://github.com/santhoshr/llama
